apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

# components:
#   - ../../components/enable-console-plugin

patches:
  - target:
      kind: Subscription
      name: openshift-gitops-operator
    path: patch-subscription.yaml
